### ISSUE TITLE
How to build the minified version?

### ISSUE THREAD

**Issue by juwul** [schmich/instascan#113]
I wanna use this [fork](https://github.com/PallasKatze/instascan/tree/webpack-compatibility) in order to get access to getUserMedia for turning on the camera's light and more options like changing the orientation which I'll hope to achieve with this fork.

**Comment by m-obi** [comment]
I want also build the minified version after insert more options (decode_any instead of decode_qr and invert the pixels). I still had download the source and add/change my things. But how can I build the minified?

**Comment by mairh** [comment]
After making your own changes you can run the following commands to generate the builds.

`gulp build` for instascan.js
`gulp release` for instascan.min.js

The files can be retrieved from `dist` folder. The folder will be generated after you run the aforementioned command.

**Comment by juwul** [comment]
Works perfect. Thanks.
