### ISSUE TITLE
Getting NotAllowedError on android

### ISSUE THREAD

**Issue by logicalgroove** [schmich/instascan#115]
On Samsung Galaxy 7 (Android 7, Chrome 63). I'm getting this error "NotAllowedError" although camera access is granted. I'm using the latest Instascan release and latest adapter.js. Any ideas why is throwing this error?

**Comment by logicalgroove** [comment]
I figured out what was causing the issue...

**Comment by williamtoshio** [comment]
What was the root cause?

**Comment by GabrielP94** [comment]
I have the same problem, How did you solve it?
