### ISSUE TITLE
home:1 Uncaught (in promise) {name: "NotSupportedError", message: "Only secure origins are allowed (see: https://goo.gl/Y0ZkNV).", constraint: undefined, toString: ƒ}

### ISSUE THREAD

**Issue by vahnmarty** [schmich/instascan#122]
It is working on my localhost, but in my live I got this error. Is it because it needed SSL?

**Comment by akehir** [comment]
@vahnmarty Yes. https://letsencrypt.org is your friend.

Check out #87 for more info.
