### ISSUE TITLE
Upcoming deprecation of URL.createObjectURL

### ISSUE THREAD

**Issue by Jebble** [schmich/instascan#139]
The console in chrome shows the following warning:
"[Deprecation] URL.createObjectURL with media streams is deprecated and will be removed in M68, around July 2018. Please use HTMLMediaElement.srcObject instead. See https://www.chromestatus.com/features/5618491470118912 for more details."

Are you planning on releasing a new version that uses the HTMLMediaElement.srcObject to prevent Instascan from working after July 2018?

**Comment by jhammann** [comment]
It seems this was already fixed quite a while ago but there was never a new release after this (check bb59b1e1bd0271d0641ea9663bbad42bab217a96).

When I clone the project, install the dependencies and run `gulp release` it creates a new release in the project's dist folder. Replace the release you use with the newly created release and the warning should be gone.

**Comment by hajime651118** [comment]
In my case, camera window is not there but camera led is on.  No scanning.  Ubuntu 16.04.  This problem starts today.  It was working few days ago.
Press F12 on FireFox, the console shows the error.
However, Demo page works well.  And I compare my instascan.min.js and Demo's one,

$ ls -al instascan.min.js /var/XXXXXXX/instascan.min.js 
-rw-rw-r-- 1 XXXXXX XXXXXX 1566037 Sep 12 19:37 instascan.min.js  => Demo
-rw-rw-r-- 1 XXXXXX XXXXXX 1561845 Mar  5  2018 /var/XXXXXX/instascan.min.js  => MY one

Different size.   But both of them contain URL.createObjectURL .

**Comment by depotnet** [comment]
> The console in chrome shows the following warning:
> "[Deprecation] URL.createObjectURL with media streams is deprecated and will be removed in M68, around July 2018. Please use HTMLMediaElement.srcObject instead. See https://www.chromestatus.com/features/5618491470118912 for more details."
> 
> Are you planning on releasing a new version that uses the HTMLMediaElement.srcObject to prevent Instascan from working after July 2018?

It is already done as @jhammann said, but not properly released.

If you want to download follow @jhammann link : [here](https://github.com/schmich/instascan/commit/bb59b1e1bd0271d0641ea9663bbad42bab217a96)

or Direct Download here : 
https://rawgit.com/schmich/instascan-builds/master/instascan.min.js

Hope it will help !

D.

**Comment by shnigi** [comment]
Using the direct download worked for me ^
