### ISSUE TITLE
Cannot access video stream (NotFoundError)

### ISSUE THREAD

**Issue by PedroVicari** [schmich/instascan#199]
The scanner was working normally on my website and suddenly it doesn't work anymore. It returns the error "Cannot access video stream (NotFoundError)". The live demo from the github page is not working for me either, no video is showing at all.

I tried to get the minified version from #139 but it doesn't do anything for me. I tried accessing the website from Google Chrome, Firefox and Microsoft Edge, but they all return the same error.

Is there any way I can get the scanner to work again?

@edit Tried cloning the master repository, running gulp release with the npm modules as stated in #177 and #197 but still getting the same error.

@edit2 This is the javascript code I use to call the scanner:

```
function scanQRCodeSepItem() {
    $('#divCamera').css('display', 'block');

    scanner = new Instascan.Scanner({
        video: document.getElementById('videoScanElement'),
        mirror: false
    });

    scanner.addListener('scan', function (content) {
        resultQRSeparacao(content);
    });

    Instascan.Camera.getCameras().then(function (cameras) {
        if (cameras.length > 0) {
            scanner.start(cameras[cameras.length - 1]);
        } else {
            $('#txtBarCodeSep').val("Nenhuma câmera encontrada.");
        }
    }).catch(function (e) {
        $('#txtBarCodeSep').val(e);
    });
}
```

**Comment by PedroVicari** [comment]
After trying a few different things it ended up just being a problem with my laptop's webcam. The scanner is working as expected.

**Comment by JsTorres97** [comment]
Hi, does it works on any Browser? because it work  local but not on my server using firefox, but in Chrome works on the server, works on IOS or Android?

**Comment by Unity-G** [comment]
I get it sometimes in an Android WebView. Not sure how to reproduce, yet.

**Comment by Anton3101** [comment]
hi...
got the same issue.. Work on local, but not in production server.

**Comment by zzador** [comment]
Same here. Deployed a webapp before the evening. Everything worked fine over the weekend in every browser (chrome, filefox, opera and iOS Safari). Suddenly without any Browser-update and without any change of the deployed app there comes this error message instead:

register:93 Error: Cannot access video stream (NotFoundError).
    at new i (VM249 instascan.min.js:8)
    at Function.<anonymous> (VM249 instascan.min.js:8)
    at n (VM249 instascan.min.js:7)
    at Generator._invoke (VM249 instascan.min.js:7)
    at Generator.e.<computed> [as throw] (VM249 instascan.min.js:7)
    at n (VM249 instascan.min.js:7)
    at r (VM249 instascan.min.js:7)
    at VM249 instascan.min.js:7

There was NO change in the webapp and there was NO change in the browser. It stopped working from one day to another. This is incredible mysterious.

**Comment by baurelk** [comment]
The Instascan ReadMe mentions Note: Chrome requires HTTPS when using the WebRTC API. Any pages using this library should be served over HTTPS. You may want to check this stackoverflow answer that discusses how to treat HTTP as secure HTTPS to help with testing in case that is affecting your setup.

https://stackoverflow.com/questions/56785180/instascan-is-not-working-on-the-js-showing-cannot-access-video-stream-typeerr
