### ISSUE TITLE
Video Stream doesn't Load.Unable to scan QR CODE

### ISSUE THREAD

**Issue by manasmanohar** [schmich/instascan#215]
PS: Instascan had been working perfectly before 6months,but now when i check it,it doesn't show the usual video stream from my camera. My site is hosted on C panel and uses LetsEncrypt for the https certificate. Usually when it worked the https icon was  in red,and there was a key icon on search bar showing, the page is trying to load unsafe scripts,(it worked perfectly during that time Nov 2018 period).

error that i get in the console:
chartist.min.js:7 Uncaught TypeError: Cannot read property 'querySelectorAll' of null
    at Object.c.createSvg (chartist.min.js:7)
    at f.d [as createChart] (chartist.min.js:7)
    at f.h (chartist.min.js:7)
instascan.min.js:9 Uncaught (in promise) TypeError: window.srcObject is not a function
    at e.<anonymous> (instascan.min.js:9)
    at t (instascan.min.js:7)
    at Generator._invoke (instascan.min.js:7)
    at Generator.e.<computed> [as next] (instascan.min.js:7)
    at t (instascan.min.js:7)
    at r (instascan.min.js:7)
    at instascan.min.js:7_

Tried the live demo,it worked. Doesnt work on any of the browser/mobile
Need to solve this by today!

https://github.com/schmich/instascan/issues/107#issuecomment-347170546_

**Comment by SudhakarPunniyakotti** [comment]
Please try this https://rawcdn.githack.com/tobiasmuehl/instascan/4224451c49a701c04de7d0de5ef356dc1f701a93/bin/instascan.min.js

**Comment by jsnayak** [comment]
I faced the same issue, I was temporarily able to resolve it by following the three links below:
1. [How-to-Generate-a-Self-Signed-Certificate-and-Private-Key-using-OpenSSL](https://helpcenter.gsx.com/hc/en-us/articles/115015960428-How-to-Generate-a-Self-Signed-Certificate-and-Private-Key-using-OpenSSL)
2. [how-do-i-setup-a-ssl-certificate-for-an-express-js-server](https://stackoverflow.com/questions/11804202/how-do-i-setup-a-ssl-certificate-for-an-express-js-server)
3. [enabling-https-on-express-js](https://stackoverflow.com/questions/11744975/enabling-https-on-express-js)

My localhost site is still seen as non-secure but the cameras are working. This can be taken as a temporary fix. My server launch looked like this:
```
const express = require('express')
var fs = require('fs');
var http = require('http');
var https = require('https');

var privateKey  = fs.readFileSync(path.resolve(__dirname, "keys/privateKey.key"), 'utf8');
var certificate = fs.readFileSync(path.resolve(__dirname, "keys/certificate.crt"), 'utf8');
var credentials = {key: privateKey, cert: certificate};

const app = new express()
var httpServer = http.createServer(app);
var httpsServer = https.createServer(credentials, app);

https.createServer({
    key: privateKey,
    cert: certificate
}, app).listen(4000);
```

**Comment by manasmanohar** [comment]
facing the same error again, unable to get video stream and the scanning doesn’t  work.
