### ISSUE TITLE
It is not working for mobile view

### ISSUE THREAD

**Issue by onyxnl** [schmich/instascan#221]
Hi All,

I want to use for my website. But it is not working on mobile. How to fix it

**Comment by bernard-ng** [comment]
hey @onyxnl which browser are you using ? I tried on google chrome (latest) and it's ok

**Comment by onyxnl** [comment]
Hi @bernard-ng ,

I tried safari and chrome on mobile(both ios version and andriod). camera is not open.
It show no camera found.
https://schmich.github.io/instascan/

**Comment by bernard-ng** [comment]
Did you allow the access to the camera ?

**Comment by onyxnl** [comment]
Yes. I already allowed. Camera is open on other scan reader project.
To be secure, could u share camera access location?
