### ISSUE TITLE
`<video>` seems to get `visibility:hidden;` after change tab and back.

### ISSUE THREAD

**Issue by notalentgeek** [schmich/instascan#43]
Here are my HTML.

    <div id="video_container" style="align-items:center;display:flex;height:100%;justify-content:center;margin-bottom:0px;margin-left:0px;margin-right:0px;margin-top:2.5px;overflow:hidden;">
      <video id="video" width="50%" autoplay loop muted preload></video>
    </div>

I am using the example codes.

    let scanner = new Instascan.Scanner({ video: document.getElementById('video') });
    scanner.addListener('scan', function (content) {
      console.log(content);
    });
    Instascan.Camera.getCameras().then(function (cameras) {
      if (cameras.length > 0) {
        scanner.start(cameras[0]);
      } else {
        console.error('No cameras found.');
      }
    }).catch(function (e) {
      console.error(e);
    });

Here is animated .gif of the problem. After I change tab (twice) the `<video>` gone although the DOM is still the same.

![http://i.imgur.com/Qr4yp3E.gif](http://i.imgur.com/Qr4yp3E.gif)

The screen shot of the `<video>` when it is gone.

![http://i.imgur.com/vz7GcKt.png](http://i.imgur.com/vz7GcKt.png)

**Comment by notalentgeek** [comment]
Further doing, commenting `//scanner.start(cameras[0]);` remove the problem but also the QR scanner. What to do?

**Comment by notalentgeek** [comment]
I use this QR reader along with face detection from TrackingJS. If I deactivate face tracking from TrackingJS the problem is gone.

What is my workaround if I need both face and QR detection?

**Comment by notalentgeek** [comment]
Are these codes the culprit?

```
  _disableScan() {
    this.video.src = ''"
```

It makes the `src` goes unknown.

**Comment by notalentgeek** [comment]
Alright, my bad... `backgroundScan:true,` fixes this.

**Comment by schmich** [comment]
@notalentgeek Yep, sorry, just saw this issue. By default, scanning is disabled when the tab is not focused to save on CPU/power consumption, but you found the flag to disable that behavior.
