### ISSUE TITLE
IOS11 - Web RTC compatability

### ISSUE THREAD

**Issue by ddwyer** [schmich/instascan#54]
Thankyou for this Great work, 
we are trying to implement this code for scanning QR code in IOS browser , we are testing with the latest IOS11 beta which has support for Web RTC.

we have access to eth camera , and webRTC getUserMedia() 

however i am getting a persistent error = Unhandled Promise Rejection: TypeError: Type error at line 13231
<code>
case 3:
                                    return this._stream = i.sent, i.abrupt("return", window.URL.createObjectURL(this._stream));
</code>

also IOS webkit version which is RTC compatible = 604
so will probably need to update line 13168

<code>
if (!navigator.userAgent.match(/Version\/(\d+).(\d+)/))
                                return e.browser = "Unsupported webkit-based browser with GUM support but no WebRTC support.", e;
                            e.browser = "safari", e.version = this.extractVersion(navigator.userAgent, /AppleWebKit\/([0-9]+)\./, 1), e.minVersion = 602
                        }
</code>

**Comment by ddwyer** [comment]
<b>$500 Bounty</b></br></br>I am unable to resolve this issue</br>Perhaps a bounty of $500 would encourage someone who is more capable than me to solve this issue.  I believe that IOS11 Beta now supports webRTC getUserMedia() . </br>You can see a working demo (only if you have iOS11 beta installed :-)</br></br> --> https://tokbox.com/developer/sdks/js/ </br></br> --> https://tokbox.com/developer/beta/safari/

**Comment by ddwyer** [comment]
This bounty is still valid - and i will honor it.
we intend to use instascan in our project , but need some support (which we are prepared to pay for) 
is there anyone who can 
[1] solve the issue 
[2] contribute open source code to the instascan project 
[3] and earn a little bit of money for your efforts

**Comment by bchr02** [comment]
+1

**Comment by lnorbert** [comment]
@ddwyer We implemented Instascan in out application recently. It's a great library and worked as expected. We didn't use the released version, but built a fresh one from master.

Here is what I did to get a fresh build to our app:

```
git clone git@github.com:schmich/instascan.git
cd instascan/
npm install gulp-cli -g
npm install
gulp release
cp dist/instascan.min.js /path/to/our/libraries/include/dir
```

Selecting a camera based on ID didn't work. It always used the front camera. We solved this by adding an ugly patch to camera.js:

```
diff --git a/src/camera.js b/src/camera.js
index 5403b3c..4a46e32 100644
--- a/src/camera.js
+++ b/src/camera.js
@@ -31,6 +31,11 @@ class Camera {
       }
     };

+    var userAgent = window.navigator.userAgent;
+    if (userAgent.match(/iPad/i) || userAgent.match(/iPhone/i)) {
+        constraints.video.facingMode = "environment";
+    }
+
     this._stream = await Camera._wrapErrors(async () => {
       return await navigator.mediaDevices.getUserMedia(constraints);
     });
```

I wouldn't create a PR for this change as it's not a nice solution. But it works, feel free to use it in your projects.

**Comment by jsmithdev** [comment]
Just fyi, in iOS11 beta the `<video />` element needs attribute  `playsinline` . Seemed to be a bug for awhile but now that it's out of beta soon idk...

https://github.com/serratus/quaggaJS/commit/e8352c7017a2f7a7500fa054f342b9689ff5d8b7#diff-afd7828cb7f3e7a1f8fe7305f50b5021

https://github.com/PaulKinlan/qrcode/commit/b79718b2391969b2291db93ba388b4c2b2f3f9d4

**Comment by ddwyer** [comment]
i can confirm that we followed the instructions by @inorbert and shazam .. like magic it's all working.
we will look to improve what we have found and report back .
-- Darren

**Comment by PallasKatze** [comment]
This is fixed in schmich/instascan/pull/78. Don't forget to **manually** include the latest [`webrtc-adapter`](https://github.com/webrtc/adapter) in your project.

**Comment by ddwyer** [comment]
@PallasKatze is a javascript GURU - this is all working now and maybe should be tested and merged ? in case anybody is interested the bounty was paid in full -- thanks for your help.

**Comment by anthonyyuan** [comment]
why do I not work it  on safari11  
 var userAgent = window.navigator.userAgent;
+    if (userAgent.match(/iPad/i) || userAgent.match(/iPhone/i)) {
+        constraints.video.facingMode = "environment";
+    }
+
     this._stream = await Camera._wrapErrors(async () => {
       return await navigator.mediaDevices.getUserMedia(constraints);
     });

**Comment by jerodfritz** [comment]
Here is a version that works compiled from https://github.com/centogram/instascan
[instascan.zip](https://github.com/schmich/instascan/files/1754622/instascan.zip)

**Comment by pandalion** [comment]
@centogram is it possible for me to use the front camera with your ios11 code? thanks :)

**Comment by jerodfritz** [comment]
@pandalion yes, but you will need to modify the code. You'll just want to change the constraints.video.facingMode constraint from "environment" to "user".

**Comment by cpapazoglou** [comment]
@centogram work like a charm. Grats!

**Comment by adelsadek1** [comment]
@centogram @hrrsppzgl  
which line I have to modify it?

**Comment by cpapazoglou** [comment]
> @centogram @hrrsppzgl
> which line I have to modify it?

@adelsadek1 
What do you really need? Have you downloaded @centogram modified code from here?
https://github.com/centogram/instascan

**Comment by adelsadek1** [comment]
@hrrsppzgl  yes I have but still not working @centogram mentioned   to modify line but I didn't which line I have to modify

**Comment by cpapazoglou** [comment]
> @hrrsppzgl yes I have but still not working @centogram mentioned to modify line but I didn't which line I have to modify

Search for 
facingMode: { exact: "environment" },
Change "environment" to "user"

![image](https://user-images.githubusercontent.com/12430020/49341333-a7efda80-f654-11e8-86d5-df69f3247b1c.png)

**Comment by Govind13100** [comment]
Hi @lnorbert 

I tried to follow your steps, 

```
git clone git@github.com:schmich/instascan.git
cd instascan/
npm install gulp-cli -g
npm install
gulp release
cp dist/instascan.min.js /path/to/our/libraries/include/dir
```

But when try the first cmd, it throws the below error 

![Screenshot 2019-07-15 at 7 20 52 PM](https://user-images.githubusercontent.com/26818036/61221292-d169fc00-a735-11e9-9da8-2237e6c9f487.png)


Please, can you help me out here?

Thank you
