### ISSUE TITLE
Adding custom function within the scanner.addListner 

### ISSUE THREAD

**Issue by ravic1995** [schmich/instascan#56]
let scanner = new Instascan.Scanner({ video: document.getElementById('preview') });
      scanner.addListener('scan', function (content) {
       this. foo(content);
        console.log(content);
      });

is there any way i can add in a function `this.foo(content)` I am using react

**Comment by schmich** [comment]
This is a quirk of JavaScript closures and `this`. The way you have it written, `this` in the anonymous function refers to the object that raised the event, which is not what you want.

You have two options:

1. Use an [ES6 arrow function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions) which binds lexically to `this`. Arrow functions are [pretty well supported](http://caniuse.com/#search=arrow%20functions), but if your target environment does not support them, you might need to cross-compile to whichever dialect of JS is supported.

```js
let scanner = new Instascan.Scanner({ video: document.getElementById('preview') });
scanner.addListener('scan', content => {
  this.foo(content);
  console.log(content);
});
```

2. Use a variable outside of your anonymous function for the `this` you're trying to refer to. This approach doesn't require any new syntax support, but it's not as clean as using arrow functions.

```js
let self = this;
let scanner = new Instascan.Scanner({ video: document.getElementById('preview') });
scanner.addListener('scan', function (content) {
  self.foo(content);
  console.log(content);
});
```
