### ISSUE TITLE
Does Instascan work with ASP.NET MVC?

### ISSUE THREAD

**Issue by cmkhoury** [schmich/instascan#58]
When I place the HTML code into my ASP.NET application, no content appears on the webpage (where instascan should appear). I am wondering if the two are compatible? Or what is the best way to implement instascan with Razor syntax?

**Comment by ParthTrehan** [comment]
Yes I have used it in my one of the project and it works just fine.
It also works with asp.net core too

**Comment by ParthTrehan** [comment]
Can you show me your code

**Comment by cmkhoury** [comment]
Never mind, there was a source pointing issue that I was able to resolve.

**Comment by robertfausk** [comment]
@cmkhoury I think you can close this issue now;)
