### ISSUE TITLE
Not working on Android 7.0, Chrome 59

### ISSUE THREAD

**Issue by lusentis** [schmich/instascan#65]
Hi, I can't get this to work on my phone (specs below).

How to reproduce:
1. open https://schmich.github.io/instascan/ in Chrome for Android
1. accept the permission prompt
1. both cameras are detected and listed in the sidebar
1. the "camera in use" icon appears in the notification area
1. no video is shown, and no QR code is captured (no message appears in DevTools, too)

Thank you for your great work!

---

**Device** Huawei Honor 6X
**Android** 7.0 (Huawei EMUI)
**Chrome** 59.0.3071.125

**User Agent** `"Mozilla/5.0 (Linux; Android 7.0; BLN-L21 Build/HONORBLN-L21) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.125 Mobile Safari/537.36"`

**Screenshot**
![5ff8d2af-6c2c-43c3-bd72-06eacb07506c](https://user-images.githubusercontent.com/950086/28887242-babcd63a-77bc-11e7-81c5-a53e6fab3819.png)

**Comment by ssc-hrep3** [comment]
Works for me with both cameras on Android 7.0.0, HTC 10, Chrome 59.0.3071.125
Chrome displays a small video camera symbol in the notification area, when the camera is running. I cannot see this icon on your screenshot. You could try to reset your camera permissions in the chrome settings (chrome settings - website - camera).

**Comment by lusentis** [comment]
Thank you, I've updated the screenshot - I tried to revoke the permission and run the example again, even rebooted the phone, but no luck.

**Comment by lusentis** [comment]
Okay, seems that some Huawei devices have issues with WebRTC.
Googling and trying other [WebRTC demos](https://webrtc.github.io/samples/) result in the same issue. (For reference, my smartphone is a Huawei Honor 6X)
Closing as unrelated to instascan, sorry for bothering you.
