### ISSUE TITLE
scan result in a input field

### ISSUE THREAD

**Issue by Mazsuu** [schmich/instascan#66]
hey ho,

first off all, im a beginner. i learning at the moment some programming languages.

i tried to use this library to scan a qr-code and put the result in a input field.
but it doesnt work.

can somebody help  or show me how to handle this problem?

thank you for your support

**Comment by mairh** [comment]
What exactly doesn't work? It would be nice if you show your code.

**Comment by Mazsuu** [comment]
sorry, but there is no code to show because i dont know how to handle it.
i just tried something with a input field.
can you show me or what i have to deliver?

**Comment by mairh** [comment]
@RahmanG 

I haven't tested the below code. I am just writing it on the fly.

Modified code from README.MD 

Using jQuery
```
<script type="text/javascript">
      let scanner = new Instascan.Scanner({ video: document.getElementById('preview') });
      scanner.addListener('scan', function (content) {
        $("#yourInputFieldId").val(content); // Pass the scanned content value to an input field
      });
      Instascan.Camera.getCameras().then(function (cameras) {
        if (cameras.length > 0) {
          scanner.start(cameras[0]);
        } else {
          console.error('No cameras found.');
        }
      }).catch(function (e) {
        console.error(e);
      });
    </script>
```

Using plain JS
```
<script type="text/javascript">
      let scanner = new Instascan.Scanner({ video: document.getElementById('preview') });
      scanner.addListener('scan', function (content) {
        document.getElementById("yourInputFieldId").value = content; // Pass the scanned content value to an input field
      });
      Instascan.Camera.getCameras().then(function (cameras) {
        if (cameras.length > 0) {
          scanner.start(cameras[0]);
        } else {
          console.error('No cameras found.');
        }
      }).catch(function (e) {
        console.error(e);
      });
    </script>
```

html
```
<input type='text' id='yourInputFieldId' />
```

**Comment by Mazsuu** [comment]
@mairh 

It works thank you very much.

i cant paste my code dont know why

**Comment by mairh** [comment]
@RahmanG Close the issue if it is working.

**Comment by schmich** [comment]
@mairh Thanks, the help is appreciated.

@RahmanG As a beginner, consider looking at some resources on JavaScript. Here are some to get you started:

- [JavaScript: The Good Parts](http://www.amazon.com/JavaScript-Good-Parts-Douglas-Crockford/dp/0596517742)
- [Eloquent JavaScript](http://www.amazon.com/Eloquent-JavaScript-Modern-Introduction-Programming/dp/1593275846)
- [Codecademy JS courses](https://www.codecademy.com/learn/javascript)
- [JS-specific Khan Academy videos](https://www.khanacademy.org/computing/computer-programming)
- [Coursera classes](https://www.coursera.org/courses?languages=en&query=javascript)
- Join a JS-specific IRC channel like [#javascript](http://irc.lc/freenode/javascript) or [#node.js](http://irc.lc/freenode/node.js/) and ask questions there

And of course, keep working on your projects. It's one of the best ways to force yourself to learn new tech. Good luck!

**Comment by Mazsuu** [comment]
@mairh @schmich thank you guys

one question left. you are using the vue framework. 
is there a special reason for that?

**Comment by mairh** [comment]
I think that's a personal choice. You can use this library with any framework you want.

**Comment by codemaker2015** [comment]
You can read QR Codes using instascan.

Copy instascan.min.js from the releases page and load with:

`<script type="text/javascript" src="instascan.min.js"></script>`
Sample code to read QR Code.

```
<!DOCTYPE html>
<html>
  <head>
    <title>QR Code Reader using Instascan</title>
    <script type="text/javascript" src="instascan.min.js"></script>
  </head>
  <body>
    <video id="preview"></video>
    <script type="text/javascript">
      let scanner = new Instascan.Scanner({ video: document.getElementById('preview') });
      scanner.addListener('scan', function (content) {
        console.log(content);
      });
      Instascan.Camera.getCameras().then(function (cameras) {
        if (cameras.length > 0) {
          scanner.start(cameras[0]);
        } else {
          console.error('No cameras found.');
        }
      }).catch(function (e) {
        console.error(e);
      });
    </script>
  </body>
</html>
```

**Comment by vaishalivc** [comment]
I am having an issue that how to implement the same in angularjs, try to find it and also saw many articles but still not getting the solution..!! Any help will be appreciate, Thank you

**Comment by caputo08** [comment]
It is bringing up the camera but not actually scanning anything can someone help me with that? The other thing I was trying to do is default to the rear camera on a phone not sure if that is an option. Thanks in advance for any help.
`<html>
<script type="text/javascript">
      let scanner = new Instascan.Scanner({ video: document.getElementById('preview') });
      scanner.addListener('scan', function (content) {
        document.getElementById("yourInputFieldId").value = content; // Pass the scanned content value to an input field
      });
      Instascan.Camera.getCameras().then(function (cameras) {
        if (cameras.length > 0) {
          scanner.start(cameras[0]);
        } else {
          console.error('No cameras found.');
        }
      }).catch(function (e) {
        console.error(e);
      });
    </script>

<input type='text' id='yourInputFieldId' />

</html>`

**Comment by syabasri** [comment]
Thanks! its work and help me even a single line of code.
