### ISSUE TITLE
Angular (CLI) compatibility

### ISSUE THREAD

**Issue by werthdavid** [schmich/instascan#68]
Hey,

anybody got it working with Angular 4 so far?
My steps were:
1. npm install --save instascan
2. import * as Instascan  from "instascan";
3. Copy the code from the example to my component

**Error 1**
Getting the errors [error1.txt](https://github.com/schmich/instascan/files/1236226/error1.txt)

**Error 2**
Then I tried including node_modules/instascan/index.js directly in .angular-cli.json in apps-->scripts but that produces [error2.txt](https://github.com/schmich/instascan/files/1236227/error2.txt)

**Error 3**
Next idea was to include the minified dist-file (instascan.min.js)  directly in .angular-cli.json in apps-->scripts but that produces [error3.txt](https://github.com/schmich/instascan/files/1236228/error3.txt)

Environment:
- Win 10 Chrome 60.0.3112.101 official x64
- angular 4.3.5
- angular-cli 1.3.0

Any suggestions?

**Comment by weirdwater** [comment]
We're experiencing the same issue in our Angular 4 application. Right now we manually remove the line which imports babel-polyfill. But this is, for obvious reasons,  not a stable/recommended fix. Just a temporary workaround to test the functionality.

**Comment by aitorllj93** [comment]
Hi,
I've created a fork removing the babel-polyfill line, it's located [here](https://github.com/aitorllj93/instascan-no-polyfill) if you want to use it

**Comment by werthdavid** [comment]
Thanks man, appreciate it. 
But I've switched to "zxing-typescript" which works much better for me. I've also adapted it for iOS11. I'll try to make an Angular library out of it when I have time.

**Comment by lifenautjoe** [comment]
@schmich Any plan on fixing this?

**Comment by werthdavid** [comment]
I made an Angular-Component with ZXing, feel free to try it out:
https://github.com/werthdavid/ngx-zxing
