### ISSUE TITLE
Feature request: Add support for Vue.js

### ISSUE THREAD

**Issue by nhim175** [schmich/instascan#76]

**Comment by mairh** [comment]
Check the hosted example (https://schmich.github.io/instascan/) which is using `Vue.JS`.

Code can be found under docs folder https://github.com/schmich/instascan/tree/master/docs

**Comment by schmich** [comment]
@nhim175 Have you checked the hosted example? There are still a lot of packaging issues with Instascan (npm, Bower, Webpack, ES5), but the minified version should work just fine with Vue. Is there a specific problem you're hitting?

@mairh Thanks again for the help.

**Comment by schmich** [comment]
Closing this due to no response. @nhim175 If you can provide more details, I can provide more help.
