### ISSUE TITLE
Mac and iOS partially working

### ISSUE THREAD

**Issue by zwily** [schmich/instascan#80]
The demo seems to work great in Safari 11 on Mac OS. Probably want to update the docs.

On iOS 11, the demo loads and it asks for Camera access, and lists both cameras as available, but just shows a black box for the camera feed.

**Comment by mairh** [comment]
@zwily For the time being, you can use this [PR](https://github.com/schmich/instascan/pull/78) to generate your own dist files in order to solve the iOS 11 issue.

After checking out the branch, run

`gulp build` for instascan.js
`gulp release` for instascan.min.js

**Comment by zwily** [comment]
Oh cool - looks like it's already in progress.  Thanks.

**Comment by anthonyyuan** [comment]
hi ,which  branch do i check ? Can u help me? On safari11
