### ISSUE TITLE
QR Code never picked up

### ISSUE THREAD

**Issue by NullVoxPopuli** [schmich/instascan#81]
![image](https://user-images.githubusercontent.com/199018/30974958-f7e5bb36-a43e-11e7-8152-e4de18be6240.png)
I'm trying to scan this using the demo, and nothing is happening?
Is this type of QR code not supported?

**Comment by adammcfadden** [comment]
@NullVoxPopuli - It looks like the QR code you have there is invalid. Comes up with nothing when ran through a decoder here: https://zxing.org/w/decode?u=https%3A%2F%2Fuser-images.githubusercontent.com%2F199018%2F30974958-f7e5bb36-a43e-11e7-8152-e4de18be6240.png

**Comment by NullVoxPopuli** [comment]
dang. ok. I've switch rendering libraries, and I'm getting much better qr codes (they work). thanks!
