### ISSUE TITLE
webpack error fs in ./node_modules/instascan/src/zxing.js

### ISSUE THREAD

**Issue by dustinhsiao21** [schmich/instascan#95]
Once We used `npm install instascan --save` to install this package, then we used webpack to build the index.js. But we got an error:
```
This dependency was not found:
* fs in ./node_modules/instascan/src/zxing.js
To install it, you can run: npm install --save fs
```
Then we followed the instruction to install the `fs` package, but in vain.

Could anyone has the same problem and how to fix it?

thank you

**Comment by sk1p** [comment]
I solved this by stubbing out the fs module, with the following in my webpack config:

    module.exports = {
        // [...]
        node: {
            fs: 'empty',
        },
        // [...]
    };

See more details in the [webpack documentation](https://webpack.js.org/configuration/node/)
